# EDA - Exploring Tables and Counts

In [2]:
import pandas as pd
import sqlite3

### Creating Connection

In [3]:
conn = sqlite3.connect("vic_crash_data.db")

### Accidents table
Contains meta information about accident date, time, week, vehicles involved, location, people injured, and target variable severity

In [4]:
accidents = pd.read_sql("select * from accidents limit 5", conn)
accidents

,accident_no,accident_date,accident_time,accident_type,day_of_week,dca_code,node_id,no_of_vehicles,no_killed,no_person_inj2,no_person_inj3,no_person_not_inj,police_attended,road_geometry,light_condition,severity,speed_zone,rma
0,T20120004516,2012-02-24,15:30:00.000000,2,6,101,249991,1,0,0,1,1,1,5,1,3,50,Local Road
1,T20120007847,2012-04-03,01:57:00.000000,1,3,130,251467,2,0,0,1,2,1,5,5,3,50,Local Road
2,T20120008205,2012-04-07,01:15:00.000000,2,7,105,251982,1,0,1,0,1,1,5,3,2,80,Arterial Highway
3,T20120008420,2012-02-16,09:15:00.000000,8,5,174,251094,1,0,0,1,0,2,5,1,3,60,Freeway
4,T20120008442,2012-04-10,10:00:00.000000,1,3,121,45652,2,0,1,2,0,1,2,1,2,70,Arterial Other

### Vehicle Table
Contains all vehicle information involved in the accident - there can be multiple vehicles involved in an accident, so an accident_no can have multiple vehicles involved

In [5]:
vehicles = pd.read_sql("Select * from vehicle_info limit 5", conn)
vehicles

,accident_no,vehicle_id,vehicle_dca_code,road_surface_type,reg_state,vehicle_type,fuel_type,no_of_cylinders,seating_capacity,occupants,driver_intent,level_of_damage
0,T20120001479,A,1.0,9.0,None,13,None,NaN,NaN,1,6.0,1
1,T20120002094,C,8.0,1.0,V,1,M,6.0,5.0,0,11.0,1
2,T20120002390,A,1.0,3.0,V,1,P,6.0,5.0,1,1.0,1
3,T20120004794,A,1.0,1.0,None,99,Z,NaN,NaN,1,99.0,9
4,T20120010082,B,2.0,1.0,V,1,P,4.0,5.0,1,15.0,4

In [6]:
count_of_vehicles = pd.read_sql("""
select count(distinct v.vehicle_id) count_of_vehicles, v.accident_no from vehicle_info as v
group by v.accident_no
limit 5
""", conn)
count_of_vehicles

   count_of_vehicles   accident_no
0                  1  T20120000009
1                  2  T20120000012
2                  2  T20120000013
3                  1  T20120000018
4                  1  T20120000021

### Person Table
Contains information about people involved in the accident, their age group, injuries and whether taken to hospital

In [7]:
person = pd.read_sql("Select * from person_info limit 5", conn)
person

,accident_no,person_id,vehicle_id,sex,age_group,inj_level,seating_position,road_user,taken_hospital
0,T20120001075,A,A,M,26-29,2,D,2,Y
1,T20120001621,C,C,U,Unknown,4,D,2,None
2,T20120002142,A,A,F,30-39,4,D,2,None
3,T20120002846,A,A,F,70+,2,D,2,Y
4,T20120003531,B,B,M,26-29,4,D,2,None

### Table Accident_Node
Contains geographical location of accident, a node_id can have multiple accidents

In [8]:
nodes = pd.read_sql("Select * from accident_node limit 5", conn)
nodes

,accident_no,node_id,road_route_1,road_name,road_type,road_name_int,road_type_int,distance_location,direction_location
0,T20230006450,205541,2510,QUEENS,ROAD,ARTHUR,STREET,51,N
1,T20190018462,589104,5790,ELTHAM-YARRA GLEN,ROAD,KANGAROO GROUND-WARRANDYTE,ROAD,7,S
2,T20140009989,356149,2820,WEST GATE,FREEWAY,BAY,TRAIL,180,NW
3,T20220007169,773905,9999,BOX,STREET,PAPERBARK,STREET,45,W
4,T20170023163,326150,9999,WOLLASTON,ROAD,SOMMERVILLE,BOULEVARD,74,N

In [10]:
count_of_accidents = pd.read_sql("""
select count(distinct a.accident_no) count_of_accidents, a.node_id from accident_node a
group by a.node_id
order by count_of_accidents desc
limit 5
""", conn)
count_of_accidents

   count_of_accidents  node_id
0                  73    36335
1                  48       -1
2                  47    65743
3                  47    10592
4                  45    45524